### ISSUE TITLE
Invalid input makes webpage frozen

### ISSUE THREAD

**Issue by Leedehai** [sheabunge/compsci#1]
Typing in letter characters, (e.g. `a`, `1a`) into the decimal field on the right side on [the Two's complement converter page](https://sheabunge.github.io/compsci/twos.html) makes the entire page frozen and later the browser tells me the website is crashed.
However, typing letter characters into the binary field on the left side is fine.

**Comment by sheabunge** [comment]
Thanks for reporting this. I've added a fix which will hopefully resolve this.
